name: CI/CD - Tic Tac Toe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: CI - Testes automatizados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt -r requirements-test.txt

      - name: Rodar Testes
        run: pytest